CREATE TABLE IF NOT EXISTS courses
(
    course_id          bigserial,
    course_description varchar(255) not null,
    course_link        varchar(255) not null,
    name_of_course     varchar(255) not null,
    course_photo       bytea        not null,
    date_of_creation   timestamp(6),
    primary key (course_id)
);

CREATE TABLE IF NOT EXISTS slider
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    slider_photo BYTEA                                   NOT NULL,
    CONSTRAINT pk_slider PRIMARY KEY (id)
);

ALTER TABLE courses
    ALTER COLUMN course_description TYPE VARCHAR(255) USING (course_description::VARCHAR(255));

ALTER TABLE events
    ALTER COLUMN description TYPE VARCHAR(255) USING (description::VARCHAR(255));

ALTER TABLE events
    ALTER COLUMN description TYPE VARCHAR(255) USING (description::VARCHAR(255));

ALTER TABLE students
    ADD COLUMN registration_date TIMESTAMP;

ALTER TABLE complaints
    ALTER COLUMN comment_id SET NOT NULL;

ALTER TABLE complaints
    ALTER COLUMN complaint_reason SET NOT NULL;

ALTER TABLE complaints
    ALTER COLUMN student_id SET NOT NULL;