CREATE TABLE IF NOT EXISTS alternate_registration_student
(
    id         BIGSERIAL GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code       VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    PRIMARY KEY (id),
    CONSTRAINT alternate_registration_student_code_unique UNIQUE (code),
    CONSTRAINT alternate_registration_student_email_unique UNIQUE (email)
);

ALTER TABLE students
    DROP COLUMN city;

ALTER TABLE events
    ALTER COLUMN date_of_event SET NOT NULL;
