CREATE TABLE IF NOT EXISTS student_friendships
(
    id         BIGSERIAL,
    friend_id  BIGINT,
    student_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT student_friend_unique
        UNIQUE (student_id, friend_id),
    CONSTRAINT friend_id_fk
        FOREIGN KEY (friend_id) REFERENCES STUDENTS,
    CONSTRAINT student_id_fk
        FOREIGN KEY (student_id) REFERENCES STUDENTS
);

CREATE TABLE IF NOT EXISTS friend_requests
(
    id          BIGSERIAL,
    status      VARCHAR(255),
    receiver_id BIGINT,
    sender_id   BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT receiver_id_fk
        FOREIGN KEY (receiver_id) REFERENCES STUDENTS,
    CONSTRAINT sender_id_fk
        FOREIGN KEY (sender_id) REFERENCES STUDENTS
);

CREATE TABLE IF NOT EXISTS event_tags
(
    event_id BIGINT NOT NULL,
    tag_id   BIGINT NOT NULL,
    CONSTRAINT pk_event_tags PRIMARY KEY (event_id, tag_id)
);

CREATE TABLE IF NOT EXISTS tags
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (id)
);

ALTER TABLE event_tags
    ADD CONSTRAINT fk_eventag_on_event FOREIGN KEY (event_id) REFERENCES events (event_id);

ALTER TABLE event_tags
    ADD CONSTRAINT fk_eventag_on_tag FOREIGN KEY (tag_id) REFERENCES tags (id);
